set default to j:\wapps9\digicel\inv\tablas
idowner='ZinterCODE'
OPEN DATABASE inven
SELECT 1
USE inemov SHARED
SELECT 2
USE inmov SHARED


SELECT 1
SET FILTER TO nudoc ='0924000010' AND codtmo = 'ST'
COPY TO c:\packing\pinemov5
SELECT 2
SET FILTER TO nudoc ='0924000010' AND codtmo = 'ST'
COPY TO c:\packing\pinmov5
SELECT 1
SET FILTER TO nudoc ='0924000011' AND codtmo = 'ST'
COPY TO c:\packing\pinemov6
SELECT 2
SET FILTER TO nudoc ='0924000011' AND codtmo = 'ST'
COPY TO c:\packing\pinmov6
SELECT 1
SET FILTER TO nudoc ='0924000012' AND codtmo = 'ST'
COPY TO c:\packing\pinemov7
SELECT 2
SET FILTER TO nudoc ='0924000012' AND codtmo = 'ST'
COPY TO c:\packing\pinmov7
SELECT 1
SET FILTER TO nudoc ='0924000013' AND codtmo = 'ST'
COPY TO c:\packing\pinemov8
SELECT 2
SET FILTER TO nudoc ='0924000013' AND codtmo = 'ST'
COPY TO c:\packing\pinmov8
SELECT 1
SET FILTER TO nudoc ='0924000014' AND codtmo = 'ST'
COPY TO c:\packing\pinemov9
SELECT 2
SET FILTER TO nudoc ='0924000014' AND codtmo = 'ST'
COPY TO c:\packing\pinmov9
SELECT 1
SET FILTER TO nudoc ='0924000015' AND codtmo = 'ST'
COPY TO c:\packing\pinemov10
SELECT 2
SET FILTER TO nudoc ='0924000015' AND codtmo = 'ST'
COPY TO c:\packing\pinmov10
SELECT 1
SET FILTER TO nudoc ='0924000016' AND codtmo = 'ST'
COPY TO c:\packing\pinemov11
SELECT 2
SET FILTER TO nudoc ='0924000016' AND codtmo = 'ST'
COPY TO c:\packing\pinmov11
SELECT 1
SET FILTER TO nudoc ='0924000022' AND codtmo = 'ST'
COPY TO c:\packing\pinemov12
SELECT 2
SET FILTER TO nudoc ='0924000022' AND codtmo = 'ST'
COPY TO c:\packing\pinmov12
SELECT 1
SET FILTER TO nudoc ='0924000023' AND codtmo = 'ST'
COPY TO c:\packing\pinemov13
SELECT 2
SET FILTER TO nudoc ='0924000023' AND codtmo = 'ST'
COPY TO c:\packing\pinmov13
SELECT 1
SET FILTER TO nudoc ='0924000025' AND codtmo = 'ST'
COPY TO c:\packing\pinemov14
SELECT 2
SET FILTER TO nudoc ='0924000025' AND codtmo = 'ST'
COPY TO c:\packing\pinmov14